// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateExpedition() {
  return window['go']['main']['App']['CreateExpedition']();
}

export function CreateLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLink'](arg1, arg2, arg3);
}

export function DeleteExpedition(arg1) {
  return window['go']['main']['App']['DeleteExpedition'](arg1);
}

export function GetExpeditionSummaries() {
  return window['go']['main']['App']['GetExpeditionSummaries']();
}

export function GetPlotterInputConfig(arg1) {
  return window['go']['main']['App']['GetPlotterInputConfig'](arg1);
}

export function GetPlotterOptions() {
  return window['go']['main']['App']['GetPlotterOptions']();
}

export function LoadExpedition(arg1) {
  return window['go']['main']['App']['LoadExpedition'](arg1);
}

export function LoadRoutes(arg1) {
  return window['go']['main']['App']['LoadRoutes'](arg1);
}

export function PlotRoute(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PlotRoute'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoveRouteFromExpedition(arg1, arg2) {
  return window['go']['main']['App']['RemoveRouteFromExpedition'](arg1, arg2);
}

export function RenameExpedition(arg1, arg2) {
  return window['go']['main']['App']['RenameExpedition'](arg1, arg2);
}
