// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateExpedition() {
  return window['go']['main']['App']['CreateExpedition']();
}

export function GetExpeditionSummaries() {
  return window['go']['main']['App']['GetExpeditionSummaries']();
}

export function LoadExpedition(arg1) {
  return window['go']['main']['App']['LoadExpedition'](arg1);
}

export function LoadRoutes(arg1) {
  return window['go']['main']['App']['LoadRoutes'](arg1);
}
