// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptGalaxy() {
  return window['go']['main']['App']['AcceptGalaxy']();
}

export function AutocompleteSystems(arg1) {
  return window['go']['main']['App']['AutocompleteSystems'](arg1);
}

export function ContinueGalaxyBuild() {
  return window['go']['main']['App']['ContinueGalaxyBuild']();
}

export function CreateExpedition() {
  return window['go']['main']['App']['CreateExpedition']();
}

export function CreateLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLink'](arg1, arg2, arg3);
}

export function DebugHilbertGroups(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DebugHilbertGroups'](arg1, arg2, arg3, arg4);
}

export function DeclineGalaxy() {
  return window['go']['main']['App']['DeclineGalaxy']();
}

export function DeleteExpedition(arg1) {
  return window['go']['main']['App']['DeleteExpedition'](arg1);
}

export function DeleteLink(arg1, arg2) {
  return window['go']['main']['App']['DeleteLink'](arg1, arg2);
}

export function EndActiveExpedition() {
  return window['go']['main']['App']['EndActiveExpedition']();
}

export function GetExpeditionSummaries() {
  return window['go']['main']['App']['GetExpeditionSummaries']();
}

export function GetGalaxyState() {
  return window['go']['main']['App']['GetGalaxyState']();
}

export function GetPlotterInputConfig(arg1) {
  return window['go']['main']['App']['GetPlotterInputConfig'](arg1);
}

export function GetPlotterOptions() {
  return window['go']['main']['App']['GetPlotterOptions']();
}

export function LoadActiveExpedition() {
  return window['go']['main']['App']['LoadActiveExpedition']();
}

export function LoadExpedition(arg1) {
  return window['go']['main']['App']['LoadExpedition'](arg1);
}

export function LoadRoutes(arg1) {
  return window['go']['main']['App']['LoadRoutes'](arg1);
}

export function PlotRoute(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PlotRoute'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoveRouteFromExpedition(arg1, arg2) {
  return window['go']['main']['App']['RemoveRouteFromExpedition'](arg1, arg2);
}

export function RenameExpedition(arg1, arg2) {
  return window['go']['main']['App']['RenameExpedition'](arg1, arg2);
}

export function StartExpedition(arg1) {
  return window['go']['main']['App']['StartExpedition'](arg1);
}

export function ValidateSystemName(arg1) {
  return window['go']['main']['App']['ValidateSystemName'](arg1);
}
