// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateExpedition():Promise<string>;

export function GetExpeditionSummaries():Promise<Array<models.ExpeditionSummary>>;

export function LoadExpedition(arg1:string):Promise<models.Expedition>;

export function LoadRoutes(arg1:string):Promise<Array<models.Route>>;
