package models

import (
	"ed-expedition/database"
	"ed-expedition/lib/vec"
	"ed-expedition/migrations"
	"maps"
	"time"
)

type FSDBoost uint8

const (
	FSDBoostNone FSDBoost = iota
	FSDBoostNeutron
	FSDBoostInjectionBasic
	FSDBoostInjectionStandard
	FSDBoostInjectionPremium
)

var AllFSDBoost = []struct {
	Value  FSDBoost
	TSName string
}{
	{FSDBoostNone, "NONE"},
	{FSDBoostNeutron, "NEUTRON"},
	{FSDBoostInjectionBasic, "INJECTION_BASIC"},
	{FSDBoostInjectionStandard, "INJECTION_STANDARD"},
	{FSDBoostInjectionPremium, "INJECTION_PREMIUM"},
}

// Route represents an immutable path segment generated by a plotter
type Route struct {
	Version         int            `json:"version"`
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Plotter         string         `json:"plotter"`
	PlotterParams   map[string]any `json:"plotter_parameters"`
	PlotterMetadata map[string]any `json:"plotter_metadata,omitempty"`
	Jumps           []RouteJump    `json:"jumps"`
	CreatedAt       time.Time      `json:"created_at"`
}

// RouteJump represents a single jump in a route
type RouteJump struct {
	SystemName string         `json:"system_name"`
	SystemID   int64          `json:"system_id"`
	Scoopable  bool           `json:"scoopable"`
	MustRefuel bool           `json:"must_refuel"`
	Distance   float64        `json:"distance"` // From previous jump (0 for first)
	FuelInTank *float64       `json:"fuel_in_tank,omitempty"`
	FuelUsed   *float64       `json:"fuel_used,omitempty"`
	FSDBoost   *FSDBoost      `json:"fsd_boost"`
	Position   *vec.Vec3      `json:"position,omitempty"`
	Meta       map[string]any `json:"meta,omitempty"`
}

func (jump *RouteJump) Clone() *RouteJump {
	var pos *vec.Vec3
	if jump.Position != nil {
		a := jump.Position.Clone()
		pos = &a
	}
	var meta map[string]any
	if jump.Meta != nil {
		meta = make(map[string]any, len(jump.Meta))
		maps.Copy(meta, jump.Meta)
	}
	return &RouteJump{
		SystemName: jump.SystemName,
		SystemID:   jump.SystemID,
		Scoopable:  jump.Scoopable,
		MustRefuel: jump.MustRefuel,
		Distance:   jump.Distance,
		FuelInTank: jump.FuelInTank,
		FuelUsed:   jump.FuelUsed,
		FSDBoost:   jump.FSDBoost,
		Position:   pos,
		Meta:       meta,
	}
}

func LoadRoute(id string) (*Route, error) {
	path := database.PathFor(database.ModelTypeRoutes, id)
	return database.ReadAndMigrateJSON[Route](path, migrations.RouteMigrations)
}

func SaveRoute(route *Route) error {
	path := database.PathFor(database.ModelTypeRoutes, route.ID)
	return database.WriteJSON(path, route)
}

func TSaveRoute(t *database.Transaction, route *Route) error {
	path := database.PathFor(database.ModelTypeRoutes, route.ID)
	return t.WriteJSON(path, route)
}
