package models

import (
	"ed-expedition/database"
	"time"
)

// Route represents an immutable path segment generated by a plotter
type Route struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Plotter         string         `json:"plotter"`
	PlotterParams   map[string]any `json:"plotter_parameters"`
	PlotterMetadata map[string]any `json:"plotter_metadata,omitempty"`
	Jumps           []RouteJump    `json:"jumps"`
	CreatedAt       time.Time      `json:"created_at"`
}

// RouteJump represents a single jump in a route
type RouteJump struct {
	SystemName string    `json:"system_name"`
	SystemID   int64     `json:"system_id"`
	Scoopable  bool      `json:"scoopable"`
	MustRefuel bool      `json:"must_refuel"`
	Distance   float64   `json:"distance"` // From previous jump (0 for first)
	FuelInTank *float64  `json:"fuel_in_tank,omitempty"`
	FuelUsed   *float64  `json:"fuel_used,omitempty"`
	Overcharge *bool     `json:"overcharge,omitempty"`
	Position   *Position `json:"position,omitempty"`
}

// Position represents 3D coordinates in light years
type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

func LoadRoute(id string) (*Route, error) {
	path, err := database.PathFor(database.ModelTypeRoutes, id)
	if err != nil {
		return nil, err
	}

	return database.ReadJSON[Route](path)
}

func SaveRoute(route *Route) error {
	path, err := database.PathFor(database.ModelTypeRoutes, route.ID)
	if err != nil {
		return err
	}

	return database.WriteJSON(path, route)
}
